In [7]:
import pandas as pd
import numpy as np
import panel as pn
pn.extension ('tabulator') # extension for creating interactive tables

import hvplot.pandas # allows us to create interactive data frames

In [8]:
df = pd.read_csv("https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv")
df

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,ghg_excluding_lucf_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
0,AFG,Afghanistan,1949,0.015,0.002,NaN,NaN,NaN,0.015,0.002,...,NaN,NaN,NaN,NaN,NaN,7624058.0,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1950,0.084,0.011,NaN,NaN,NaN,0.021,0.003,...,NaN,NaN,NaN,NaN,NaN,7752117.0,9.421400e+09,NaN,NaN,NaN
2,AFG,Afghanistan,1951,0.092,0.012,NaN,NaN,NaN,0.026,0.003,...,NaN,NaN,NaN,NaN,NaN,7840151.0,9.692280e+09,NaN,NaN,NaN
3,AFG,Afghanistan,1952,0.092,0.012,NaN,NaN,NaN,0.032,0.004,...,NaN,NaN,NaN,NaN,NaN,7935996.0,1.001733e+10,NaN,NaN,NaN
4,AFG,Afghanistan,1953,0.106,0.013,NaN,NaN,NaN,0.038,0.005,...,NaN,NaN,NaN,NaN,NaN,8039684.0,1.063052e+10,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25984,ZWE,Zimbabwe,2016,10.738,0.765,1.415,0.639,0.046,6.959,0.496,...,2.076,11.50,0.820,6.21,0.443,14030338.0,2.096179e+10,46.666,3326.073,2.226
25985,ZWE,Zimbabwe,2017,9.582,0.673,1.666,0.678,0.048,5.665,0.398,...,2.023,11.62,0.816,6.35,0.446,14236599.0,2.194784e+10,45.936,3226.617,2.093
25986,ZWE,Zimbabwe,2018,11.854,0.821,1.308,0.697,0.048,7.101,0.492,...,2.173,11.96,0.828,6.59,0.456,14438812.0,2.271535e+10,47.502,3289.887,2.091
25987,ZWE,Zimbabwe,2019,10.949,0.748,1.473,0.697,0.048,6.020,0.411,...,NaN,NaN,NaN,NaN,NaN,14645473.0,NaN,49.427,3374.877,NaN
25988,ZWE,Zimbabwe,2020,10.531,0.709,NaN,0.697,0.047,6.257,0.421,...,NaN,NaN,NaN,NaN,NaN,14862927.0,NaN,NaN,NaN,NaN

In [17]:
df1 = pd.read_csv("owid-co2-data.csv")
df1

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,ghg_excluding_lucf_per_capita,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp
0,AFG,Afghanistan,1949,0.015,0.002,NaN,NaN,NaN,0.015,0.002,...,NaN,NaN,NaN,NaN,NaN,7624058.0,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1950,0.084,0.011,NaN,NaN,NaN,0.021,0.003,...,NaN,NaN,NaN,NaN,NaN,7752117.0,9.421400e+09,NaN,NaN,NaN
2,AFG,Afghanistan,1951,0.092,0.012,NaN,NaN,NaN,0.026,0.003,...,NaN,NaN,NaN,NaN,NaN,7840151.0,9.692280e+09,NaN,NaN,NaN
3,AFG,Afghanistan,1952,0.092,0.012,NaN,NaN,NaN,0.032,0.004,...,NaN,NaN,NaN,NaN,NaN,7935996.0,1.001733e+10,NaN,NaN,NaN
4,AFG,Afghanistan,1953,0.106,0.013,NaN,NaN,NaN,0.038,0.005,...,NaN,NaN,NaN,NaN,NaN,8039684.0,1.063052e+10,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25984,ZWE,Zimbabwe,2016,10.738,0.765,1.415,0.639,0.046,6.959,0.496,...,2.076,11.50,0.820,6.21,0.443,14030338.0,2.096179e+10,46.666,3326.073,2.226
25985,ZWE,Zimbabwe,2017,9.582,0.673,1.666,0.678,0.048,5.665,0.398,...,2.023,11.62,0.816,6.35,0.446,14236599.0,2.194784e+10,45.936,3226.617,2.093
25986,ZWE,Zimbabwe,2018,11.854,0.821,1.308,0.697,0.048,7.101,0.492,...,2.173,11.96,0.828,6.59,0.456,14438812.0,2.271535e+10,47.502,3289.887,2.091
25987,ZWE,Zimbabwe,2019,10.949,0.748,1.473,0.697,0.048,6.020,0.411,...,NaN,NaN,NaN,NaN,NaN,14645473.0,NaN,49.427,3374.877,NaN
25988,ZWE,Zimbabwe,2020,10.531,0.709,NaN,0.697,0.047,6.257,0.421,...,NaN,NaN,NaN,NaN,NaN,14862927.0,NaN,NaN,NaN,NaN

In [18]:
df.columns

Index(['iso_code', 'country', 'year', 'co2', 'co2_per_capita', 'trade_co2',
       'cement_co2', 'cement_co2_per_capita', 'coal_co2',
       'coal_co2_per_capita', 'flaring_co2', 'flaring_co2_per_capita',
       'gas_co2', 'gas_co2_per_capita', 'oil_co2', 'oil_co2_per_capita',
       'other_industry_co2', 'other_co2_per_capita', 'co2_growth_prct',
       'co2_growth_abs', 'co2_per_gdp', 'co2_per_unit_energy',
       'consumption_co2', 'consumption_co2_per_capita',
       'consumption_co2_per_gdp', 'cumulative_co2', 'cumulative_cement_co2',
       'cumulative_coal_co2', 'cumulative_flaring_co2', 'cumulative_gas_co2',
       'cumulative_oil_co2', 'cumulative_other_co2', 'trade_co2_share',
       'share_global_co2', 'share_global_cement_co2', 'share_global_coal_co2',
       'share_global_flaring_co2', 'share_global_gas_co2',
       'share_global_oil_co2', 'share_global_other_co2',
       'share_global_cumulative_co2', 'share_global_cumulative_cement_co2',
       'share_global_cumulative_coal_co2',
       'share_global_cumulative_flaring_co2',
       'share_global_cumulative_gas_co2', 'share_global_cumulative_oil_co2',
       'share_global_cumulative_other_co2', 'total_ghg', 'ghg_per_capita',
       'total_ghg_excluding_lucf', 'ghg_excluding_lucf_per_capita', 'methane',
       'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita',
       'population', 'gdp', 'primary_energy_consumption', 'energy_per_capita',
       'energy_per_gdp', 'gdp per capita'],
      dtype='object')

## 1. Some minor data processing

In [19]:
# Fill N/A with zero (0) and create GDP per capita column

df=df.fillna(0)
df['gdp per capita'] = np.where(df['population']!=0,df['gdp']/df['population'],0) # creates another column, gdp per capita.
# where population is not equal to zero, divide the gdp column by population column

In [20]:
df # check the last column - gdp per capita

,iso_code,country,year,co2,co2_per_capita,trade_co2,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,...,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,primary_energy_consumption,energy_per_capita,energy_per_gdp,gdp per capita
0,AFG,Afghanistan,1949,0.015,0.002,0.000,0.000,0.000,0.015,0.002,...,0.00,0.000,0.00,0.000,7624058.0,0.000000e+00,0.000,0.000,0.000,0.000000
1,AFG,Afghanistan,1950,0.084,0.011,0.000,0.000,0.000,0.021,0.003,...,0.00,0.000,0.00,0.000,7752117.0,9.421400e+09,0.000,0.000,0.000,1215.332543
2,AFG,Afghanistan,1951,0.092,0.012,0.000,0.000,0.000,0.026,0.003,...,0.00,0.000,0.00,0.000,7840151.0,9.692280e+09,0.000,0.000,0.000,1236.236369
3,AFG,Afghanistan,1952,0.092,0.012,0.000,0.000,0.000,0.032,0.004,...,0.00,0.000,0.00,0.000,7935996.0,1.001733e+10,0.000,0.000,0.000,1262.264378
4,AFG,Afghanistan,1953,0.106,0.013,0.000,0.000,0.000,0.038,0.005,...,0.00,0.000,0.00,0.000,8039684.0,1.063052e+10,0.000,0.000,0.000,1322.255925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25984,ZWE,Zimbabwe,2016,10.738,0.765,1.415,0.639,0.046,6.959,0.496,...,11.50,0.820,6.21,0.443,14030338.0,2.096179e+10,46.666,3326.073,2.226,1494.033433
25985,ZWE,Zimbabwe,2017,9.582,0.673,1.666,0.678,0.048,5.665,0.398,...,11.62,0.816,6.35,0.446,14236599.0,2.194784e+10,45.936,3226.617,2.093,1541.648846
25986,ZWE,Zimbabwe,2018,11.854,0.821,1.308,0.697,0.048,7.101,0.492,...,11.96,0.828,6.59,0.456,14438812.0,2.271535e+10,47.502,3289.887,2.091,1573.214825
25987,ZWE,Zimbabwe,2019,10.949,0.748,1.473,0.697,0.048,6.020,0.411,...,0.00,0.000,0.00,0.000,14645473.0,0.000000e+00,49.427,3374.877,0.000,0.000000
25988,ZWE,Zimbabwe,2020,10.531,0.709,0.000,0.697,0.047,6.257,0.421,...,0.00,0.000,0.00,0.000,14862927.0,0.000000e+00,0.000,0.000,0.000,0.000000

In [21]:
# Make DataFrame pipeline interactive
idf = df.interactive()

### CO2 Emissions over time by continent

In [22]:
# Define panel widgets
year_slider = pn.widgets.IntSlider(name="Year Slider",start=1750,end=2020,step=5,value=1850)
year_slider

BokehModel(combine_events=True, render_bundle={'docs_json': {'282626df-a5f7-4a79-9ec5-6cbab88e48e2': {'defs': …

IntSlider(end=2020, name='Year Slider', start=1750, step=5, value=1850)

In [23]:
# Radio buttons for CO2 measures
yaxis_co2 = pn.widgets.RadioButtonGroup(
    name="Y Axis",
    options=['co2','co2 per capita',],
    button_type = 'success'
)

In [24]:
# connect the data pipeline with the widgets, so that as the widgets are changed/interacted with, the underlining data should also change.

idf = df.interactive()
continents = ['World','Asia','Oceania','Europe','Africa','North America','South America','Antarctica']

co2_pipeline = (
    idf[
        (idf.year <= year_slider) &
        (idf.country.isin(continents))
    ]
    .groupby(['country','year'])[yaxis_co2].mean()
    .to_frame()
    .reset_index()
    .sort_values(by='year')
    .reset_index(drop=True)
)

In [25]:
co2_pipeline

BokehModel(combine_events=True, render_bundle={'docs_json': {'990910d8-0c62-47d4-9e7e-51795bb46f9c': {'defs': …

In [26]:
co2_plot = co2_pipeline.hvplot(x='year',by='country',y=yaxis_co2,line_width=2,title='CO2 emissions by continent')
co2_plot

BokehModel(combine_events=True, render_bundle={'docs_json': {'86321cbb-d4c6-404b-b392-f5f5d44db7c6': {'defs': …

# Table - CO2 Emissions over time by continent

In [27]:
co2_table = co2_pipeline.pipe(pn.widgets.Tabulator,pagination='remote',page_size=10,sizing_mode='stretch_width')
co2_table

BokehModel(combine_events=True, render_bundle={'docs_json': {'46bc38a9-50d6-4dce-8d23-9fca4fc3a85b': {'defs': …

# CO2 vs GDP Scatter plot

In [33]:
# creating data pipeline for the scatter plot first
co2_vs_gdp_scatterplot_pipeline = (
    idf[(idf.year == year_slider) & (~ (idf.country.isin(continents)))]
    .groupby(['country', 'year', 'gdp per capita'])['co2'].mean()
    .to_frame()
    .reset_index()
    .sort_values(by='year')  
    .reset_index(drop=True)
)

## Plotting the scatter plot

In [36]:
# plotting based on the pipeline data

co2_vs_gdp_scatterplot = co2_vs_gdp_scatterplot_pipeline.hvplot(x='gdp per capita', 
                                                                y='co2', 
                                                                by='country', 
                                                                size=80, kind="scatter", 
                                                                alpha=0.7,
                                                                legend=False, 
                                                                height=500, 
                                                                width=500)
co2_vs_gdp_scatterplot

BokehModel(combine_events=True, render_bundle={'docs_json': {'ecc93dd8-5466-408a-8deb-056baf551fbc': {'defs': …

In [37]:
yaxis_co2_source = pn.widgets.RadioButtonGroup(
    name='Y axis', 
    options=['coal_co2', 'oil_co2', 'gas_co2'], 
    button_type='success'
)

continents_excl_world = ['Asia', 'Oceania', 'Europe', 'Africa', 'North America', 'South America', 'Antarctica']

co2_source_bar_pipeline = (
    idf[
        (idf.year == year_slider) &
        (idf.country.isin(continents_excl_world))
    ]
    .groupby(['year', 'country'])[yaxis_co2_source].sum()
    .to_frame()
    .reset_index()
    .sort_values(by='year')  
    .reset_index(drop=True)
)

In [38]:
co2_source_bar_plot = co2_source_bar_pipeline.hvplot(kind='bar', 
                                                     x='country', 
                                                     y=yaxis_co2_source, 
                                                     title='CO2 source by continent')
co2_source_bar_plot

BokehModel(combine_events=True, render_bundle={'docs_json': {'8b791898-d8ce-474f-bc49-071f989805ec': {'defs': …

In [46]:
#Layout using Template
template = pn.template.FastListTemplate(
    title='World CO2 emission dashboard', 
    sidebar=[pn.pane.Markdown("# CO2 Emissions and Climate Change"), 
             pn.pane.Markdown("#### Carbon dioxide emissions are the primary driver of global climate change. Its widely recognised that to avoid the worst impacts of climate change, the world needs to urgently reduce emissions. But, how this responsibility is shared between regions, countries, and individuals has been an endless point of contention in international discussions."), 
             #pn.pane.PNG('climate_day.jpg', sizing_mode='scale_both'),
             pn.pane.Markdown("## Settings"),   
             year_slider],
    main=[pn.Row(pn.Column(yaxis_co2, 
                           co2_plot.panel(width=700), margin=(0,25)), 
                 co2_table.panel(width=500)), 
          pn.Row(pn.Column(co2_vs_gdp_scatterplot.panel(width=600), margin=(0,25)), 
                 pn.Column(yaxis_co2_source, co2_source_bar_plot.panel(width=600)))],
    accent_base_color="#88d8b0",
    header_background="#88d8b0",
)
# template.show()
template.servable();